name: EC2 deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      env:
        # GitHub Secrets 사용
        EC2_PRIVATE_SECRET: ${{ secrets.EC2_PRIVATE_SECRET }}
        EC2_USER: "ubuntu"
        EC2_HOST: ${{ secrets.EC2_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: |
        echo "EC2 deploy start"

        # pem key 생성
        echo "${EC2_PRIVATE_SECRET}" > ec2-private-key.pem
        chmod 400 ec2-private-key.pem

        # 환경 변수 설정
        ssh -o StrictHostKeyChecking=no -i ec2-private-key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
        EOF
        
        # 배포 스크립트 실행
        ssh -o StrictHostKeyChecking=no -i ec2-private-key.pem ${EC2_USER}@${EC2_HOST} "bash -s" < runserver.sh